### ISSUE TITLE
pyRDDLGym-rl 0.2 is not compatible with pyRDDLGym 2.0

### ISSUE THREAD

**Issue by nhuet** [pyrddlgym-project/pyRDDLGym-rl#7]
The last release pyRDDLGym-rl 0.2 is compatible  with the last release of pyRDDLGym (2.1) but not with the previous one (2.0) even though it requires only  'pyRDDLGym>=2.0'.

I stumble upon this when creating a python 3.12 environment as  pyRDDLGym 2.1 requires python<3.12.

When calling `reset()` method of a `SimplifiedActionRDDLEnv` environment with pyRDDLGym-rl 0.2 + pyRDDLGym 2.0, I get:
```
E           AttributeError: 'SimplifiedActionRDDLEnv' object has no attribute 'seeds'. Did you mean: 'seed'?
```

The simplest solution would be to update setup.py with 
```
        install_requires=[
          'pyRDDLGym>=2.1'
        ],
```

**Comment by mike-gimelfarb** [comment]
Thanks for pointing that out. It is now fixed on the github repo, but there is unfortunately no way to fix it for version 0.2 on pypi that I know of. We will make some updates and upload everything there again with version 0.3. Users should be recommended to update to pyrddlgym 2.1. I am hoping we can fix your other isuse on that repo site ;)
